<div class="product-info col-sm-7">
  <p class="availability in-stock"><span class="iconorange">BACKORDER</span></p>
  <p class="order_ship">
    <span class="paddingtop"><span class="icon iconorange">icon</span>Available for order (ships 3-4 days)</span>
    <abbr title="<p>This item is on backorder or it is on the way from our supplier and will be delivered to our warehouse shortly.</p>
      <p>You may order now and it will be delivered as soon as it arrives in our warehouse.</p>
      <p>You will be periodically updated&nbsp;on the delivery progress and you may cancel your order at anytime.</p>" rel="tooltip"><i class="fa fa-question-circle fa-lg" aria-hidden="true"></i></abbr>
  </p>
  <div class="product-right-bottom-wrapper">
    <div class="product-shipping-form">
      <div class="item"><em class="fa-fw fa fa-truck"></em><strong><span class="heading">This item qualifies for FREE shipping.</span></strong></div>
      <div class="item"><em class="fa-fw fa fa-thumbs-o-up"></em><strong>Any other items in cart with this product also ship for FREE.</strong></div>
      <div class="item"><em class="fa-fw fa fa-thumbs-o-up"></em><span class="heading">This product is covered by an Australian Replacement Warranty.</span></div>
      <div class="item"><em class="fa-fw fa fa-thumbs-o-up"></em><span class="heading">30 Days Money Back Guarantee. <a href="http://support.macfixit.com.au/article/48-30-day-money-back-guarantee" target="_blank">Click here</a> for more details.</span></div>
    </div>
  </div>
  <p class="pro-code">Product code: IDE2-OWCSSDMLP120</p>
  <p class="no-rating"><a class="goto-reviews" onclick="goreview(jQuery(this))">Be the first to review this product</a></p>
  <div class="box-brand">
    <a href="https://www.macfixit.com.au/owc" title="Click to see more products from OWC"><img src="https://res.cloudinary.com/macfixit-australia-pty-ltd/image/upload/dpr_1.0,f_auto,fl_lossy,q_auto/media/infortis/attributes/manufacturer/owc.png" alt="OWC" width="210" height="50"></a>
  </div>
  <div class="short-description">
    <h2>Highlights</h2>
    <div class="std">High Performance internal MLC Flash storage with 7% Over Provisioned Redundancy for laptops that use a 2.5" IDE/ATA hard drive. 3 Year OWC Warranty.</div>
  </div>
  <!-- Check whether the plugin is enabled -->
  <!-- AddThis Button BEGIN -->
  <!-- AddThis API Config -->
  <script type="text/javascript">
    var addthis_product = 'mag-1.0.1';
    var addthis_config 	= {
    pubid : 'unknown'
    , ui_use_css : false 
    
    }
  </script>
  <!-- AddThis API Config END -->
  <div class="sharing-tool-area">
    <div class="addthis_toolbox addthis_default_style addthis_32x32_style">
      <a class="addthis_button_facebook addthis_button_preferred_1 at300b" title="Facebook" href="#">
        <span class="at-icon-wrapper" style="background-color: rgb(59, 89, 152); line-height: 32px; height: 32px; width: 32px;">
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" aria-labelledby="at-svg-facebook-2" title="Facebook" alt="Facebook" class="at-icon at-icon-facebook" style="width: 32px; height: 32px;">
            <title id="at-svg-facebook-2">Facebook</title>
            <g>
              <path d="M22 5.16c-.406-.054-1.806-.16-3.43-.16-3.4 0-5.733 1.825-5.733 5.17v2.882H9v3.913h3.837V27h4.604V16.965h3.823l.587-3.913h-4.41v-2.5c0-1.123.347-1.903 2.198-1.903H22V5.16z" fill-rule="evenodd"></path>
            </g>
          </svg>
        </span>
      </a>
      <a class="addthis_button_twitter addthis_button_preferred_2 at300b" title="Twitter" href="#">
        <span class="at-icon-wrapper" style="background-color: rgb(29, 161, 242); line-height: 32px; height: 32px; width: 32px;">
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" aria-labelledby="at-svg-twitter-3" title="Twitter" alt="Twitter" class="at-icon at-icon-twitter" style="width: 32px; height: 32px;">
            <title id="at-svg-twitter-3">Twitter</title>
            <g>
              <path d="M27.996 10.116c-.81.36-1.68.602-2.592.71a4.526 4.526 0 0 0 1.984-2.496 9.037 9.037 0 0 1-2.866 1.095 4.513 4.513 0 0 0-7.69 4.116 12.81 12.81 0 0 1-9.3-4.715 4.49 4.49 0 0 0-.612 2.27 4.51 4.51 0 0 0 2.008 3.755 4.495 4.495 0 0 1-2.044-.564v.057a4.515 4.515 0 0 0 3.62 4.425 4.52 4.52 0 0 1-2.04.077 4.517 4.517 0 0 0 4.217 3.134 9.055 9.055 0 0 1-5.604 1.93A9.18 9.18 0 0 1 6 23.85a12.773 12.773 0 0 0 6.918 2.027c8.3 0 12.84-6.876 12.84-12.84 0-.195-.005-.39-.014-.583a9.172 9.172 0 0 0 2.252-2.336" fill-rule="evenodd"></path>
            </g>
          </svg>
        </span>
      </a>
      <a class="addthis_button_print addthis_button_preferred_3 at300b" title="Print" href="#">
        <span class="at-icon-wrapper" style="background-color: rgb(115, 138, 141); line-height: 32px; height: 32px; width: 32px;">
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" aria-labelledby="at-svg-print-4" title="Print" alt="Print" class="at-icon at-icon-print" style="width: 32px; height: 32px;">
            <title id="at-svg-print-4">Print</title>
            <g>
              <path d="M24.67 10.62h-2.86V7.49H10.82v3.12H7.95c-.5 0-.9.4-.9.9v7.66h3.77v1.31L15 24.66h6.81v-5.44h3.77v-7.7c-.01-.5-.41-.9-.91-.9zM11.88 8.56h8.86v2.06h-8.86V8.56zm10.98 9.18h-1.05v-2.1h-1.06v7.96H16.4c-1.58 0-.82-3.74-.82-3.74s-3.65.89-3.69-.78v-3.43h-1.06v2.06H9.77v-3.58h13.09v3.61zm.75-4.91c-.4 0-.72-.32-.72-.72s.32-.72.72-.72c.4 0 .72.32.72.72s-.32.72-.72.72zm-4.12 2.96h-6.1v1.06h6.1v-1.06zm-6.11 3.15h6.1v-1.06h-6.1v1.06z"></path>
            </g>
          </svg>
        </span>
      </a>
      <a class="addthis_button_email addthis_button_preferred_4 at300b" target="_blank" title="Email" href="#">
        <span class="at-icon-wrapper" style="background-color: rgb(132, 132, 132); line-height: 32px; height: 32px; width: 32px;">
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" aria-labelledby="at-svg-email-5" title="Email" alt="Email" class="at-icon at-icon-email" style="width: 32px; height: 32px;">
            <title id="at-svg-email-5">Email</title>
            <g>
              <g fill-rule="evenodd"></g>
              <path d="M27 22.757c0 1.24-.988 2.243-2.19 2.243H7.19C5.98 25 5 23.994 5 22.757V13.67c0-.556.39-.773.855-.496l8.78 5.238c.782.467 1.95.467 2.73 0l8.78-5.238c.472-.28.855-.063.855.495v9.087z"></path>
              <path d="M27 9.243C27 8.006 26.02 7 24.81 7H7.19C5.988 7 5 8.004 5 9.243v.465c0 .554.385 1.232.857 1.514l9.61 5.733c.267.16.8.16 1.067 0l9.61-5.733c.473-.283.856-.96.856-1.514v-.465z"></path>
            </g>
          </svg>
        </span>
      </a>
      <a class="addthis_button_compact at300m" href="#">
        <span class="at-icon-wrapper" style="background-color: rgb(255, 101, 80); line-height: 32px; height: 32px; width: 32px;">
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" aria-labelledby="at-svg-addthis-1" title="More" alt="More" class="at-icon at-icon-addthis" style="width: 32px; height: 32px;">
            <title id="at-svg-addthis-1">Addthis</title>
            <g>
              <path d="M18 14V8h-4v6H8v4h6v6h4v-6h6v-4h-6z" fill-rule="evenodd"></path>
            </g>
          </svg>
        </span>
      </a>
      <div class="atclear"></div>
    </div>
  </div>
  <script type="text/javascript" src="https://s7.addthis.com/js/300/addthis_widget.js"></script>
  <!-- AddThis Button END -->
  <div class="pro-view-wishlist">
    <a href="https://www.macfixit.com.au/wishlist/index/add/product/2842/form_key/Kwx9XfnDcS858p0n/" class="wishlist">Add to Wishlist            </a>
  </div>
</div>